set -g mouse on

set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"

# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0
set-option -g focus-events on

# set -g status-position top
set -g set-clipboard on      # use system clipboard
set -g base-index 1
set -g status-interval 3     # update the status bar every 3 seconds
set -g detach-on-destroy off
set -g renumber-windows on

# customize status right
set -g status-right ""

# customize status left
set -g status-left "  #[fg=#ff9e64,bold]#S "
set -ga status-left "#(gitmux -cfg $HOME/.config/tmux/gitmux_tokyonight.yml)"
set -g status-justify center
set -g status-left-length 200    # increase length (from 10)
set -g status-position top       # macOS / darwin style
set -g status-style '' # transparent
set -g window-status-current-format '#[fg=#0db9d7, bold] #W'
set -g window-status-format '#[fg=#737aa2, bg=default,bold] #W'
set -g default-terminal "${TERM}"
set -g message-command-style bg=default,fg=default
set -g message-style bg=default,fg=default
setw -g mode-keys vi
set -g pane-active-border-style 'fg=default,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# key bindings for sessionx
set -g @sessionx-bind 'o'
#### Key bindings
set-window-option -g mode-keys vi


# Reload settings
bind r source-file ~/.config/tmux/.tmux.conf \; display "Reloaded!"

# sesh
bind-key "T" run-shell "sesh connect $(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)'
)"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

#split window 
bind -r v split-window -h
# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

#lazygit
bind g new-window -c "#{pane_current_path}" -n "󰳏 " lazygit
unbind-key -n C-a f
bind-key - C-a f new-window -c "#{pane_current_path}" -n "󰳏 " yazi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'omerxx/tmux-sessionx'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

