set -g mouse on

set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"

# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0
set-option -g focus-events on

# set -g status-position top
set -g set-clipboard on      # use system clipboard
set -g base-index 1
set -g status-interval 3     # update the status bar every 3 seconds
set -g detach-on-destroy off
set -g renumber-windows on

# customize status right
set -g status-right ""

# customize status left
set -g status-left "#[fg=#8FBCBB,bold]#S "
set -ga status-left "#(gitmux -cfg $HOME/.config/tmux/gitmux_nord.yml)"
set -g status-justify left
set -g status-left-length 200    # increase length (from 10)
set -g status-position top       # macOS / darwin style
set -g status-style '' # transparent
set -g window-status-current-format '#[fg=#8FBCBB, bold] #W'
set -g window-status-format '#[fg=#D8DEE9, bg=default,bold] #W'
set -g default-terminal "${TERM}"
set -g message-command-style bg=default,fg=default
set -g message-style bg=default,fg=default
setw -g mode-keys vi
set -g pane-active-border-style 'fg=default,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

#### Key bindings
set-window-option -g mode-keys vi


# Reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"
# sessionx
set -g @sessionx-bind 'O'
# sesh
bind-key "o" run-shell "sesh connect $(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '  ' \
		--header '  ^a=󰯬  ^t=󰰥  ^x=󰰷  ^d= ' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(󱐌  )+reload(sesh list -z)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(󱐌   )+reload(sesh list)'
)"

set -g @fzf-url-bind 'O'
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
set -g @t-bind 'T'
set -g @t-fzf-find-binding 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)'
set -g @t-fzf-prompt '🔭 '
set -g @tmux-nerd-font-window-name-shell-icon ''
set -g @tmux-nerd-font-window-name-show-name false
# Open current directory
bind -r e kill-pane -a

#split window 
bind -r v split-window -h
# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

bind g new-window -c "#{session_directory}" -n "󰳏  lazygit" lazygit
bind f new-window -c "#{session_directory}" -n "  yazi" yazi
bind t new-window -c "#{session_directory}" -n "  dooit" dooit
bind e new-window -c "#{session_directory}" -n "󰡨 lazydocker" lazydocker

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
# set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator' # <ctrl>+hjkl
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin '2kabhishek/tmux-tilit'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.config/tmux/plugins/tpm/tpm" # run tpm (always end of file)

