set -g mouse on
set -g default-terminal "xterm-256color"
set-option -g terminal-overrides ',xterm-256color:RGB'
# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0
set-option -g focus-events on
# set -g status-position top
set -g set-clipboard on      # use system clipboard
set -g base-index 1
set -g status-interval 3     # update the status bar every 3 seconds
set -g detach-on-destroy off
set -g renumber-windows on
set -g status-left "#[fg=#d33682,bold]  #S "
set -g status-right ''
set -g status-justify left
set -g status-left-length 200    # increase length (from 10)
set -g status-right-length 200    # increase length (from 10)
set -g status-position top       # macOS / darwin style
set -g status-style '' # transparent
set -g window-status-current-format '#[fg=magenta,bold]   #I #W'
set -g window-status-format '#[fg=gray,bg=#04141C,bold] #I #W'
set -g default-terminal "${TERM}"
set -g message-command-style bg=default,fg=yellow
set -g message-style bg=default,fg=yellow
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# key bindings for t-smart-tmux-session-manager
set -g @t-bind "s"
set -g @t-fzf-prompt ' '

#### Key bindings
set-window-option -g mode-keys vi

# Reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

#split window 
bind -r v split-window -h 
# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
